# Generated by Django 5.2.12 on 2026-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_patientcompanioncheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('patient', 'Paciente'), ('companion', 'Acompanhante'), ('professional', 'Profissional'), ('volunteer', 'Voluntário')], default='patient', max_length=20, verbose_name='Tipo de pessoa'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cidade'),
        ),
    ]
