# Generated by Django 5.2.12 on 2026-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_person_type_alter_person_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('closed', 'Encerrado')], default='open', max_length=10, verbose_name='Status'),
        ),
    ]
